### ISSUE TITLE
Nezha's version has expired

### ISSUE THREAD

**Issue by zasitonbyl** [KnowledgeDiscovery/rca_baselines#2]
https://github.com/IntelligentDDS/Nezha/commit/461b5b2b150552903ba1fc3416f16e7d52e33f94
I tried to install Nezha but it failed. I noticed that the official code has been updated and the use of Orange3 has been removed. Your project is doing well, and I noticed that you have published multiple new papers. Will you continue to update this project?

**Comment by lemma-rca** [comment]
Thank you for your interest in our work and for informing us about the updates to the Nezha code. We will update our code to reflect these changes and continue to keep our project up-to-date.

**Comment by sexiy** [comment]
Thank you for your sharing. I am a newcomer to this field and have just begun conducting research and surveys. While reading the paper MULAN, I sought out the code implementation and stumbled upon your series of works. However, I noticed that the code for MULAN has not been made public yet. Will the code for MULAN be updated in the future?

**Comment by KnowledgeDiscovery** [comment]
Thank you for your interested in MULAN paper. Unfortunately, due to the company policy, we are not allowed to release the source code of MULAN to public. However, we are happy to answer any questions you might have during the implementation.
